---
# tasks for OS-update

- name: os-update - package update 
  yum: update_cache=yes cache_valid_time=3600

- name: os-update - package upgrade 
  yum: upgrade=dist

- name: os-update - autoremove 
  yum: autoremove=yes
